# Generated by Django 5.2.6 on 2025-09-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, help_text='Upload a small icon image for this category', null=True, upload_to='category_icons/'),
        ),
    ]
