# Generated by Django 5.2.6 on 2025-09-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('deactive', 'Deactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Dairy, Bread & Eggs', 'Dairy, Bread & Eggs'), ('Snacks & Munchies', 'Snacks & Munchies'), ('Fruits & Vegetables', 'Fruits & Vegetables'), ('Bakery & Biscuits', 'Bakery & Biscuits'), ('Instant Food', 'Instant Food'), ('Tea, Coffee & Drinks', 'Tea, Coffee & Drinks'), ('Atta, Rice & Dal', 'Atta, Rice & Dal'), ('Masala, Oil & More', 'Masala, Oil & More'), ('Sweet Tooth', 'Sweet Tooth'), ('Frozen Veg', 'Frozen Veg'), ('Frozen Non-Veg', 'Frozen Non-Veg')], max_length=100),
        ),
    ]
