# Generated by Django 5.2.6 on 2025-09-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('distance', models.CharField(blank=True, max_length=50)),
                ('delivery', models.BooleanField(default=True)),
                ('pickup', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stores/logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
