# Generated by Django 5.2.6 on 2025-09-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='slug',
        ),
        migrations.AlterField(
            model_name='store',
            name='delivery',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='pickup',
            field=models.TextField(default=False),
        ),
    ]
