# Generated by Django 5.2.6 on 2025-09-11 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_store_slug_alter_store_delivery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='pickup',
            new_name='location',
        ),
    ]
