# Generated by Django 5.2.6 on 2025-09-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_rename_pickup_store_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='delivery',
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
